#!/bin/bash
cd /home/pi
echo
echo Mission to Mars Pi Setup
echo
echo OS Update
echo
sudo apt-get update
echo
echo Installing Iceweasel
echo
sudo apt-get -y --force-yes install iceweasel
echo
echo Installing Arduino IDE
echo
sudo apt-get -y --force-yes install arduino
cp /usr/share/applications/arduino.desktop /home/pi/Desktop/arduino.desktop
sudo sed -i -- 's/serial.port=.*/serial.port=\/dev\/ttyUSB0/' /usr/share/arduino/lib/preferences.txt
sudo sed -i -- 's/board =.*/board = nano328/' /usr/share/arduino/lib/preferences.txt
sudo sed -i -- 's/debug_rate=.*/debug_rate=115200/' /usr/share/arduino/lib/preferences.txt
sudo sed -i -- 's/font=.*/font=Monospaced,plain,21/' /usr/share/arduino/lib/preferences.txt
echo
echo Installing Arduino NewPing Library
echo
wget https://bitbucket.org/teckel12/arduino-new-ping/downloads/NewPing_v1.7.zip
sudo unzip NewPing_v1.7.zip -d /usr/share/arduino/libraries/
rm NewPing_v1.7.zip
echo
echo Installing Arduino Unit Test Library
echo
wget https://github.com/mmurdoch/arduinounit/archive/v2.1.1.zip
unzip v2.1.1.zip
sudo cp -R /home/pi/arduinounit-2.1.1/src/ /usr/share/arduino/libraries/ArduinoUnit/
rm v2.1.1.zip
rm -fr arduinounit-2.1.1
echo
echo Installing gitg
echo
sudo apt-get -y --force-yes install gitg
cp /usr/share/applications/gitg.desktop /home/pi/Desktop/gitg.desktop
echo
echo Installing RPiMobTimer
echo
wget https://github.com/SteveAmor/RPiMobTimer/archive/master.zip
unzip master.zip
rm /home/pi/master.zip
sudo apt-get -y --force-yes install xdotool
echo
echo Updating autostart
echo
mkdir /home/pi/.config/autostart
mv /home/pi/RPiMobTimer-master/MobTimerAutostart.desktop /home/pi/.config/autostart/
echo
echo Downloading Datasheets
echo
mkdir /home/pi/Datasheets
wget http://store.invensense.com/datasheets/invensense/MPU-6050_DataSheet_V3%204.pdf -P /home/pi/Datasheets/
wget https://www.olimex.com/Products/Modules/Sensors/MOD-MPU6050/resources/RM-MPU-60xxA_rev_4.pdf -P /home/pi/Datasheets/
wget http://www51.honeywell.com/aero/common/documents/myaerospacecatalog-documents/Defense_Brochures-documents/HMC5883L_3-Axis_Digital_Compass_IC.pdf  -P /home/pi/Datasheets/
wget http://www.micropik.com/PDF/HCSR04.pdf -P /home/pi/Datasheets/
echo
echo Clean up
echo
rm -fr /home/pi/.git
rm -fr /home/pi/Mission-to-Mars-RPi-Initialisation
echo
echo Finished
